### ISSUE TITLE
Customise

### ISSUE THREAD

**Issue by Muk211** [nocona71/obsidian-literature-note#3]
I had been struggling for a few days to get my Obsidian+Zotero workflow going. Then I found your Zotero Integration and your template and it has everything I could wish for. There are only some small but crucial changes I'd personally like. I was hoping you could help me, since I have no clue about coding.

1. The highlights should not be grouped into different colors but rather be cronological order in order of the article (but keep the different color callouts).
2.  I would also like to change the highlight names to my own liking, I tried but it broke the template somehow. Green = Examples. Yellow = Relevant. Red = Important. Blue = Definitions. Black = Statistics. Purple = Questions. 
3. Make comments to highlights appear more clearly, perhaps by having the comments to the highlights under of the callout?
4. I had another template that automatically imported the abstract. I am not sure if it's possible with this addon?

- Christoffer

**Comment by Muk211** [comment]
Another idea: It would be great if you could highlight with e.g. margenta and then it would convert it into ## headlines. This way you could structure your notes a bit aswell.

**Comment by nocona71** [comment]
Thanks for your suggestions.

ad 1) changed in release v1.0.5
ad 2) up to now these settings are "hardcoded" in the template and can be changed there to your preference:
![image](https://user-images.githubusercontent.com/63201084/233189654-68ff90f7-b4c4-47a5-9091-fa5a769e2be8.png)
ad 3) changed in release v1.0.5
ad 4) changed in release v1.0.5
