### ISSUE TITLE
Feature request: Update literature note

### ISSUE THREAD

**Issue by huachuman** [nocona71/obsidian-literature-note#4]
It would be nice to have a way to update annotations. Usually I have more than one annotating session with any given PDF item.

**Comment by nocona71** [comment]
Actually this is already part of the solution. The "persist" feature of https://github.com/mgmeyers/obsidian-zotero-integration/ already provides a way to continously update annotations (and notes). See https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/docs/Templating.md for details.
