### ISSUE TITLE
Live edit compatibility?

### ISSUE THREAD

**Issue by huachuman** [nocona71/obsidian-literature-note#6]
First of all thank you for this fantastic tool. 

I wanted to ask about live edit. I know thatI always work in live edit mode and never use the preview mode, and a lot of us depend on the ability to seamlessly interact with out notes as they are rendered.

Unfortunately this plugin seems to have issues in the live edit mode, such as displaying "%% begin notes %%" for example.

Are there any plans to address this? Is it even possible? 

Thanks again.

**Comment by nocona71** [comment]
Hi @huachuman, thanks for reaching out. 
Unfrotunately, I am not aware of a way to circumvent this. 
Thanks
