### ISSUE TITLE
Annotation Color - Conversion to Text

### ISSUE THREAD

**Issue by Calbe009** [nocona71/obsidian-literature-note#7]
Hi there,

Firstly, thanks so much for this template. I've been wrestling with this for 2 weeks, and this template is a godsend!

I'm having an issue getting the annotation type (Agree, Disagree, Important etc.) to come through. In your display image in the readme, the red boxes are preceeded by "Disagree" which I find very helpful. I believe my template is failing to trigger this if criteria but I can't figure out why. (I'm also contemplating including the annotation.color in the textbox instead, but I'm sure just using the style for a bit will ingraine it for me)

I believe it to be this section:
`{%- for annotation in newAnnotations -%}
{# {% if loop.first -%} #}
{# #### {{colorToName(color | lower)}} #}
{# {% endif %} #}
> [!annotation-{% if annotation.color %}{% if colorToColorCategory[annotation.color].length > 0*%}{{colorToColorCategory[annotation.color]}}{% else %}yellow{% endif %}]{% endif %} `

I've checked the zotero hex values and there's no change.

If this isn't the right place to ask, please remove this with my already **abundant** thanks!!!
Calbe

**Comment by nocona71** [comment]
Hi @Calbe009, I appreciate you like the templates. The thread #8 might help you.

Best
