### ISSUE TITLE
Mapping alternate hex values to closest colors

### ISSUE THREAD

**Issue by bhanu151** [nocona71/obsidian-literature-note#8]
Hi!
Firstly, kudos on creating this elegant template! It has been very helpful.

I have several pdfs that were annotated using alternate pdf-viewers. So the hex codes don't always match the Zotero highlights hex codes. But they still fall into the broad color categories of red, blue, green, etc.

When I add these pdfs to Zotero and extract annotations, they get extracted smoothly. However all of them are classified and displayed as yellow highlights. Is there a way the color mapping could include a range of hex codes rather than mapping a single hex code to a color value?

Any leads on this would be helpful. Thank you very much!

**Comment by nocona71** [comment]
Hi @bhanu151, thanks fpr your interest in the templates.

In the most recent relase I use the colorCategory instead of the color (HEX-value). This might work better for you.

Thanks
